---

- name: Install Docker
  hosts: local
  roles:
    - name: geerlingguy.docker
      become: true
      failed_when: no
    - name: geerlingguy.pip
      become: true
      vars:
        pip_package: python3-pip
        pip_install_packages:
          - name: docker
          - name: pyopenssl
  tasks:
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        append: yes
        groups:
          - docker
      become: true
    - name: reset ssh connection to make user changes effective
      meta: reset_connection


- name: Install HEXAA to local host
  hosts: local
  module_defaults:
    docker_container:
        pull: true
        restart_policy: "{{ docker_restart_policy }}"
        networks_cli_compatible: no
  pre_tasks:
    - name: Create env network
      docker_network:
        name: hexaa_env
      tags: [always]
    - name: Read and set host IP
      set_fact:
        gateway_ip: "{{ docker_network.IPAM.Config[0].Gateway }}"
      tags: [always]
    - debug:
        msg: "Local IP: {{ gateway_ip }}"
  roles:
     - role: ansible-role-hexaa-backend
       tags: backend
     - role: ansible-role-hexaa-frontend
       tags: frontend
     - role: ansible-role-hexaa-test-env
       tags: testenv

