---

- import_playbook: local_test_env.yml

- name: Install HEXAA to local host
  hosts: local
  roles:
     - role: ansible-role-hexaa-backend
     - role: ansible-role-hexaa-frontend

- name: Restart mdx  # so that it fetches metadata again
  hosts: local
  tasks:
    - docker_container:
        name: "metadata.{{ LOCAL_DOMAIN }}"
        restart: yes
      tags: [always]
