---
- name: Install HEXAA to local host
  hosts: local

  roles:
     - role: ansible-role-hexaa-backend
       tags:
         - backend
     - role: ansible-role-hexaa-frontend
       tags:
         - frontend
- import_playbook: local_test_env.yml
