---
- name: Install HEXAA to local host
  hosts: local
  tasks:

  roles:
     - role: ansible-role-hexaa-backend
       tags:
         - backend
     - role: ansible-role-hexaa-frontend
       tags:
         - frontend
