- geerlingguy.docker
- geerlingguy.pip

- src: https://github.com/hexaaproject/ansible-role-hexaa-frontend.git
  scm: git
- src: https://github.com/hexaaproject/ansible-role-hexaa-backend.git
  scm: git

- src: https://github.com/hexaaproject/ansible-role-attributes.git
  scm: git
- src: https://github.com/hexaaproject/ansible-role-idp.git
  scm: git
