@startuml
package "Hexaa CORE" {
    package "backend" {
        [hexaa-backend-web]
        note top: Nginx
        [hexaa-backend]
        note top: PHP-fpm
        [hexaa-service-entityids-generator]
        [mysql]
        [memcached]
        [hexaa-ssp-aa]
        note top: SimpleSAMLphp
    }
    note top of backend: ansible-role-backend
    package "frontend" {
        [hexaa-frontend]
        note top: PHP-fpm
        [hexaa-frontend-web]
        note top: Apache HTTPD + Shibboleth SP
    }
    note top of frontend: ansible-role-frontend
}

@enduml
